apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-config
data:
  ENVIRONMENT: "production"
  # O scanner deve pegar essa linha pelo nome 'SECRET' e pela entropia do valor
  APP_SECRET: "b3Blbi1maW5hbmNlLWJhc2lsLTIwMjYtc2VjcmV0LWtleS12YWx1ZQ=="
  APP_SECRET: "senhaAqui@@20012"



